# Generated by Django 3.0.6 on 2020-08-10 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20200721_1751'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='priority',
            field=models.IntegerField(default=0),
        ),
    ]
